// ⚠️ PLACEHOLDER — NOT A REAL FIREBASE CONFIGURATION. ⚠️
//
// This file normally is GENERATED by the FlutterFire CLI. It could not be
// generated automatically because the Firebase project "cognicare-ner" is not
// accessible from the currently authenticated Firebase account
// (triveninarayanpriy@gmail.com). The values below are dummy placeholders that
// let the app compile; `Firebase.initializeApp` will NOT connect to a real
// backend until this file is regenerated.
//
// To replace this file with real values, create/get access to the project and
// then run (from the cognicare_ner/ directory):
//
//   flutterfire configure --project=cognicare-ner --platforms=android,web \
//     --android-package-name=com.cognicare.ner.cognicare_ner \
//     --out=lib/firebase_options.dart
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform: '
          '$defaultTargetPlatform. This project targets android and web only.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAql6kSDn9p86ckKkAXhNtuC6JTnhopeIg',
    appId: '1:185179890828:web:5505d863adc3ca383ec7a9',
    messagingSenderId: '185179890828',
    projectId: 'cognicare-ner',
    authDomain: 'cognicare-ner.firebaseapp.com',
    storageBucket: 'cognicare-ner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIdYSn8sqzXMTHuwOKct69mBoxAU2vzzg',
    appId: '1:185179890828:android:d432072001a038003ec7a9',
    messagingSenderId: '185179890828',
    projectId: 'cognicare-ner',
    storageBucket: 'cognicare-ner.firebasestorage.app',
  );
}
